services:
  # BACK-END
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_URL: jdbc:mysql://mysql-container/code_inspect_db
      DB_USERNAME: root
      DB_PASSWORD: asdfasdf
    depends_on:
      - mysql-container
  # FRONT-END
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 80:5173
    depends_on:
      - backend
  # DATABASE
  mysql-container:
    image: mysql:8.0.28-oracle
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: code_inspect_db
      MYSQL_ROOT_PASSWORD: asdfasdf
      MYSQL_PASSWORD: asdfasdf
volumes:
  db-data:
