services:
  # BACK-END
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_URL: jdbc:mysql://mysql-container/code_inspect_db
      DB_USERNAME: root
      DB_PASSWORD: asdfasdf
    depends_on:
      - mysql-container
      - kafka-container
  # FRONT-END
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 80:5173
    depends_on:
      - backend
      - ws-server
  # DATABASE
  mysql-container:
    image: mysql:8.0.28-oracle
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: code_inspect_db
      MYSQL_ROOT_PASSWORD: asdfasdf
      MYSQL_PASSWORD: asdfasdf
  # WEB-SOCKET
  ws-server:
    build:
      context: ws-server
      dockerfile: Dockerfile
    ports:
      - 7078:7078
    environment:
      WS_ENV_WS_PORT: 7078
      WS_ENV_KAFKA_HOSTNAME: kafka-container
    depends_on:
      - kafka-container
  # KAFKA
  kafka-container:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka-container
      KAFKA_CREATE_TOPICS: "db-changes:1:1"
volumes:
  db-data:
