apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: default
data:
  KAFKA_ADVERTISED_HOST_NAME: kafka-service
  KAFKA_CREATE_TOPICS: "db-changes:1:1"
  KAFKA_ZOOKEEPER_CONNECT: zookeeper-service:2181
  KAFKA_ADVERTISED_PORT: "9092"
  KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
  KAFKA_AUTO_OFFSET_RESET: earliest
