apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: wurstmeister/kafka
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ADVERTISED_HOST_NAME
          valueFrom:
            configMapKeyRef:
              name: kafka-config
              key: KAFKA_ADVERTISED_HOST_NAME
        - name: KAFKA_CREATE_TOPICS
          valueFrom:
            configMapKeyRef:
              name: kafka-config
              key: KAFKA_CREATE_TOPICS
        - name: KAFKA_ZOOKEEPER_CONNECT
          valueFrom:
            configMapKeyRef:
              name: kafka-config
              key: KAFKA_ZOOKEEPER_CONNECT
        - name: KAFKA_ADVERTISED_PORT
          valueFrom:
            configMapKeyRef:
              name: kafka-config
              key: KAFKA_ADVERTISED_PORT
        - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
          valueFrom:
            configMapKeyRef:
              name: kafka-config
              key: KAFKA_AUTO_CREATE_TOPICS_ENABLE
        - name: KAFKA_AUTO_OFFSET_RESET
          valueFrom:
            configMapKeyRef:
              name: kafka-config
              key: KAFKA_AUTO_OFFSET_RESET










---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  type: ClusterIP
  ports:
  - port: 9092
    targetPort: 9092
  selector:
    app: kafka
